### ISSUE TITLE
last build terminates just after start (dev branch)

### ISSUE THREAD

**Issue by pnb69** [CREDITSCOM/contract-executor#1]
![contract-executor](https://user-images.githubusercontent.com/52343838/61829903-375b2f80-ae6a-11e9-8026-18b02c0d4f23.jpg)

System: Windows 10 Pro

**Comment by botstorm** [comment]
Hello. The executor does not need to run in a separate window. It runs in the node window automatically.
You need to run only Node and desktop-wallet

**Comment by pnb69** [comment]
@botstorm Strange, because at the beginning I started it from cs_launher and contract executor appeared for a while and closed itself. client was displaing info that is waiting for conttact executor. Previous version of contract executor was running in separate window

**Comment by pnb69** [comment]
Thx again for your help @botstorm.
For information at github
I added to config.ini following lines:

    [api]
    executor_command=java -jar contract-executor.jar
    apiexec_port=9070
    ajax_port=8081

Contract executor now is started by client.exe.
No need to start it separately.
To run it properly it must be last build of contract-executor.
